clients:
  image_size:
    width: 320
    height: 240

  frame_rate: 20

  parameters_below_threshold:
    gain: 2
    sample_time: 1

  parameters_above_threshold:
    gain: 0.1
    sample_time: 0.1

  activation_threshold: 15
